apiVersion: v1
kind: Pod
metadata:
  name: priv-pod-2
spec:
  containers:
  - name: centos
    image: centos:centos7.9.2009
    command: ['sh', '-c', 'sleep 999']
    securityContext:
      privileged: false
      allowPrivilegeEscalation: false
