apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: require-run-as-nonroot
  namespace: training9-sec
spec:
  validationFailureAction: Enforce
  rules:
  - name: run-as-user
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: >-
        Running as root is not allowed. Either the field spec.securityContext.runAsNonRoot
        must be set to `true`, or the fields spec.containers[*].securityContext.runAsNonRoot,
        spec.initContainers[*].securityContext.runAsNonRoot, and spec.ephemeralContainers[*].securityContext.runAsNonRoot
        must be set to `true`.          
      anyPattern:
      - spec:
          securityContext:
            runAsNonRoot: "true"
          =(ephemeralContainers):
          - =(securityContext):
              =(runAsNonRoot): "true"
          =(initContainers):
          - =(securityContext):
              =(runAsNonRoot): "true"
          containers:
          - =(securityContext):
              =(runAsNonRoot): "true"
      - spec:
          =(ephemeralContainers):
          - securityContext:
              runAsNonRoot: "true"
          =(initContainers):
          - securityContext:
              runAsNonRoot: "true"
          containers:
          - securityContext:
              runAsNonRoot: "true"
  - name: run-as-non-root-user
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: >-
        Running as root is not allowed. The fields spec.securityContext.runAsUser,
        spec.containers[*].securityContext.runAsUser, spec.initContainers[*].securityContext.runAsUser,
        and spec.ephemeralContainers[*].securityContext.runAsUser must be unset or
        set to a number greater than zero.
      anyPattern:
      - spec:
          securityContext:
            runAsUser: ">0"
          =(ephemeralContainers):
          - =(securityContext):
              =(runAsUser): ">0"
          =(initContainers):
          - =(securityContext):
              =(runAsUser): ">0"
          containers:
          - =(securityContext):
              =(runAsUser): ">0"
      - spec:
          =(ephemeralContainers):
          - securityContext:
              runAsUser: ">0"
          =(initContainers):
          - securityContext:
              runAsUser: ">0"
          containers:
          - securityContext:
              runAsUser: ">0"
