apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: require-harbor-only
  namespace: training9-bookinfo-dev
spec:
  validationFailureAction: Enforce
  rules:
  - name: harboronly
    match:
      resources:
        names:
        - bookinfo-dev-ratings
        - bookinfo-dev-details
        kinds:
        - Deployment
    validate:
      message: "eieieieieiei.          "
      pattern:
      - spec:
          template:
            spec:
              containers:
              - image: "harbor.demo.calllab.co.th/*"
