apiVersion: v1
kind: LimitRange
metadata:
  name: limit-constraint
spec:
  limits:
  - defaultRequest:
      cpu: 100m
      memory: 20Mi
    default:
      cpu: 100m
      memory: 100Mi

    min:
      cpu: 100m
      memory: 20Mi
    max:
      cpu: 1000m
      memory: 500Mi
    type: Container
