apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-readwrite
  namespace: training9-bookinfo-dev
rules:
- apiGroups:
  - ""
  - "apps"
  - "networking.k8s.io"
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbac-readwrite-binding
  namespace: training9-bookinfo-dev
roleRef:
  kind: Role
  name: role-readwrite
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: training9
    namespace: training9-bookinfo-dev
